[theme]
base = "dark"

# Core palette (optimized for medical imaging contrast)
backgroundColor = "#030a0a"         
secondaryBackgroundColor = "#0b3f43"   
primaryColor = "#6dadbe"                 
textColor = "#cedadb"                   

font = "monospace"

borderColor = "#30363d"
dataframeHeaderBackgroundColor = "#21262d"
dataframeBorderColor = "#30363d"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
